HOSTS:
  ubuntu-server-1204-x64:
    roles:
      - master
    platform: ubuntu-12.04-amd64
    box: puppetlabs/ubuntu-12.04-64-nocm
    #box: wywy-ubuntu-12.04.5
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-12.04-64-nocm
    #box_url: http://files.munich.wywy.com/vagrant/box/wywy-ubuntu-12.04.5.box
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type: foss
